### ISSUE TITLE
Add the date of the history, creation and remove for listing

### ISSUE THREAD

**Issue by GDemay** [GDemay/aviv-technical-test#17]
> la date de mise en ligne (ou au moins la date à laquelle on l’a vue pour la première fois)
> la date de retrait du site (ou au moins la dernière date à laquelle on l’a vue)
> l’historique complet des prix.

Add 2 fields for listings with creation and deleted field

Create a new table for history price

# history_price

id | listing_id | price| date  
1| 95995 | 200 000| 26/08/1995
2| 95995 | 215 | 26/08/2010
3| 95995 | 300 000| 20/08/2015
4| 95994 | 100 000| 20/08/2015

History price has a listing_price id linked to listing table 
id is a premary key

**Comment by GDemay** [comment]
```
     logger.debug("Successfully updated listing_id:", listing.listing_id)
pricemap_1    | Message: 'Successfully updated listing_id:'
pricemap_1    | Arguments: ('1969928561',)
pricemap_1    | --- Logging error ---
pricemap_1    | Traceback (most recent call last):
pricemap_1    |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
pricemap_1    |     msg = self.format(record)
pricemap_1    |   File "/usr/local/lib/python3.8/logging/__init__.py", line 929, in format
pricemap_1    |     return fmt.format(record)
pricemap_1    |   File "/usr/local/lib/python3.8/logging/__init__.py", line 668, in format
pricemap_1    |     record.message = record.getMessage()
pricemap_1    |   File "/usr/local/lib/python3.8/logging/__init__.py", line 373, in getMessage
pricemap_1    |     msg = msg % self.args
pricemap_1    | TypeError: not all arguments converted during string formatting
pricemap_1    | Call stack:
pricemap_1    |   File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
pricemap_1    |     self._bootstrap_inner()
pricemap_1    |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
pricemap_1    |     self.run()
pricemap_1    |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
pricemap_1    |     self._target(*self._args, **self._kwargs)
pricemap_1    |   File "/usr/local/lib/python3.8/socketserver.py", line 683, in process_request_thread
pricemap_1    |     self.finish_request(request, client_address)
pricemap_1    |   File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
pricemap_1    |     self.RequestHandlerClass(request, client_address, self)
pricemap_1    |   File "/usr/local/lib/python3.8/socketserver.py", line 747, in __init__
pricemap_1    |     self.handle()
pricemap_1    |   File "/home/pricemap/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 363, in handle
pricemap_1    |     super().handle()
pricemap_1    |   File "/usr/local/lib/python3.8/http/server.py", line 427, in handle
pricemap_1    |     self.handle_one_request()
pricemap_1    |   File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
pricemap_1    |     method()
pricemap_1    |   File "/home/pricemap/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 335, in run_wsgi
pricemap_1    |     execute(self.server.app)
pricemap_1    |   File "/home/pricemap/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 324, in execute
pricemap_1    |     for data in application_iter:
pricemap_1    |   File "/home/pricemap/.local/lib/python3.8/site-packages/werkzeug/debug/__init__.py", line 329, in debug_application
pricemap_1    |     app_iter = self.app(environ, start_response)
pricemap_1    |   File "/home/pricemap/.local/lib/python3.8/site-packages/flask/app.py", line 2548, in __call__
pricemap_1    |     return self.wsgi_app(environ, start_response)
pricemap_1    |   File "/home/pricemap/.local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
pricemap_1    |     response = self.full_dispatch_request()
pricemap_1    |   File "/home/pricemap/.local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
pricemap_1    |     rv = self.dispatch_request()
pricemap_1    |   File "/home/pricemap/.local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
pricemap_1    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
pricemap_1    |   File "/home/pricemap/app/pricemap/app.py", line 44, in update_data
pricemap_1    |     update()
pricemap_1    |   File "/home/pricemap/app/pricemap/update_data.py", line 32, in update
pricemap_1    |     generate_listing_in_database(
pricemap_1    |   File "/home/pricemap/app/pricemap/update_data.py", line 60, in generate_listing_in_database
pricemap_1    |     crud_listing.update(apartment)
pricemap_1    |   File "/home/pricemap/app/pricemap/crud/listing.py", line 109, in update
pricemap_1    |     logger.debug("Successfully updated listing_id:", listing.listing_id)
pricemap_1    | Message: 'Successfully updated listing_id:'
```

**Comment by GDemay** [comment]
Adding history_price table
Add a row in history_price when creating a listing row
Add a row in history_price if we update a new price to the history_price
